### PR TITLE
print only content

### PR DESCRIPTION
**Pull request by paskal**
This change intended to make it easier to print site by hiding anything but content (including comments). In default installation it hides recent posts and footer.
Before this PR: [pdf](http://dump.bitcheese.net/files/ejofale/before_change.pdf)
After this PR: [pdf](http://dump.bitcheese.net/files/acekemo/after_change.pdf)
I can consider including footer to print. Will be happy to hear other people's opinion on my idea.

### CODE REVIEW

**Comment by kAworu** [comment]
To me it's OK to hide the footer, anyone wanting different may / should comment and/or create another PR.

Feel free to merge this PR and close it ! :+1:

**Comment by paskal** [comment]
Styles of content printed are slightly different before and after my path, I'll recheck and merge it. Thank you!

**Comment by kAworu** [comment]
any update on this ?

**Comment by kAworu** [comment]
Thanks !

**Pull request merged**
