### PR TITLE
Horizontal scrollbar

### PR DESCRIPTION
**Pull request by pozitron57**
No more horizontal scrollbar at collapsed navbar

### CODE REVIEW

**Comment by kAworu** [comment]
Hi @pozitron57 

Thank you for your report. I can't reproduce the "horizontal scrollbar at collapsed navbar" on the demo blog at http://kaworu.github.io/octostrap3/, do you have an example website / code of the bug ?

About the diff, we're unlikely to patch aynthing that belongs to the boostrap's dist stuff as it would be overrided on bootstrap update. The issue is either a bootstrap bug and it should be "bounced" upstream or we have a bug and will fix it in files/code we "own".

Best regards,
Alex.

**Comment by pozitron57** [comment]
Hi @kAworu 

I do see this horizontal scrollbar at  http://kaworu.github.io/octostrap3/
Here are screenshots I made just now (Chrome 42.0.2311.152;  Firefox 38.0, I am using Ubuntu 14.10 with XFCE):
Chrome http://www.zimagez.com/zimage/screenshot2015-05-1913-16-37.php
Firefox http://www.zimagez.com/zimage/screenshot2015-05-1913-15-37.php
I am talking about horizontal scrollbar just below "RSS".

By the way, once I noticed that on Mac OS (don't remember which browser, either Safari or Firefox) in similar situation browser didn't show the scrollbar, nevertheless it was possible to scroll the area.

OK, I understood why it is not the best way to make corrections in bootstrap.css. 

Best,
Sergey

**Comment by kAworu** [comment]
Hi @pozitron57,

Thank you, I could indeed reproduce the bug when the menu is open. After a quick look it seems to be the search form: it should not be in the list but "outside" (as in this bootstrap example http://getbootstrap.com/examples/jumbotron/). Can you take a look ?

Thank you,
Alex.

**Comment by pozitron57** [comment]
@kAworu, sorry, I forgot to mention that scrollbar appears when the menu is open! I'll take a look later on.

**Comment by kAworu** [comment]
Hi @pozitron57,

Let me know if you can find the time to look at this issue. If not no problem, I'll address it on the next Bootstrap release.

Regards,
Alex.

**Comment by pozitron57** [comment]
Hi Alex, I am sorry for the delay. Unfortunately I cannot check now but I think that adding to `sass/custom/_styles.scss` something like this 

      .navbar-nav {
         margin: 0px 0px !important;
      }

will fix the issue. Maybe even without `!important`. Or you don't want this file to be changed?

**Comment by kAworu** [comment]
Hi @pozitron57,

While the CSS fix you provided in this PR may work, I believe there is a more "elegant" solution fixing the HTML markup to match the example provided in my previous comment. At least I wish to avoid using `!important`.

I'll take a look about the markup.

**Comment by kAworu** [comment]
@pozitron57,

Can you confirm that 1f44b29 fixed it ?

**Comment by pozitron57** [comment]
@kAworu, I'll be away from my computer with octopress next 10 days and now I can't check.

**Comment by kAworu** [comment]
@pozitron57,

no problem, feel free to comment back when you get the time to test if the commit did not fix it.

**Comment by pozitron57** [comment]
@kAworu,

just reinstalled the theme. Bug is fixed.

**Pull request closed without merging**
